- ./:
    - LINK.md:
        - description: Add Trinket link to LINK.md
          check: MatchFileFragment
          options:
            fragment: trinket.io
            count: 1
    - main.py:
        - description: Document your variable assignments and deployments in code comments
          check: CountSingleLineComments
          options:
            language: "Python"
            count: 13
            exact: false
        - description: draw at least 15 text, pyramid, box, or sphere shapes
          check: MatchFileRegex
          options:
            regex: (text|pyramid|box|sphere)
            count: 15
        - description: declare at least three string or number variables
          check: MatchFileRegex
          options:
            regex: \w+\s*=\s*(\d*\.*\d+|\".*\")
            count: 3
        - description: use at least two different variables containing color and apply them to shapes
          check: MatchFileRegex
          options:
            regex: color\s*\=\s*[a-z]
            count: 2
    - IDEATION.md:
      - description: IDEATION.md contains two paragraphs. 
        check: CountFileParagraphs
        options:
          count: 2
      - description: IDEATION.md contains at least 150 words
        check: CountFileWords
        options:
          count: 150
      - description: IDEATION.md contains at least one image
        check: MatchFileFragment
        options:
          fragment: '!['
          count: 1
      - description: IDEATION.md contains at least one reference link
        check: MatchFileFragment
        options:
          fragment: http
          count: 1
    - REFLECTION.md:
      - description: REFLECTION.md contains at least 200 words
        check: CountFileWords
        options:
          count: 200
      

     
