- ./:
    - LINK.md:
        - description: Add Trinket link to LINK.md
          check: MatchFileFragment
          options:
            fragment: trinket.io
            count: 1
    - main.py:
        - description: Declare a variable and assign it a value at least three times
          check: MatchFileRegex
          options:
            regex: (\w+)\s*=\s*(.*)
            count: 3
        - decription: Document your variable assignments and deployments
          check: CountSingleLineComments
          options:
            count: 9
    - IDEATION.md:
      - description: IDEATION.md contains two paragraphs. 
            check: CountFileParagraphs
            options:
              count: 2
          - description: IDEATION.md contains at least 150 words
            check: CountFileWords
            options:
              count: 250
          - description: IDEATION.md contains at least one image
            check: MatchFileFragment
            options:
              fragment: '!['
              count: 1
          - description: IDEATION.md contains at least one reference link
            check: MatchFileFragment
            options:
              fragment: http
              count: 1
      

     
